export const DModalityHead = [
  {
    field: 'id',
    label: 'No',
    type: 'text',
    width: 40
  },
  {
    field: 'ae_title',
    label: 'AE Title',
    type: "text",
    width: 300
  },
  {
    field: 'ip_address',
    label: 'IP Address',
    type: "text",
    width: 120
  },
  {
    field: 'port',
    label: 'Port',
    type: 'text',
    width: 100
  },
  {
    field: 'device_name',
    label: 'Device Name',
    type: 'text',
    width: 120
  },
  {
    field: 'description',
    label: 'Description',
    type: 'text',
    width: 800
  },
];

export const DModalityColumnValues = [
  {
    "id": 1,
    "ae_title": "X-Ray",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 2,
    "ae_title": "Dicom-Burnner",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 3,
    "ae_title": "GinkGo",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 4,
    "ae_title": "CT-01",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 5,
    "ae_title": "X-Ray",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 6,
    "ae_title": "Dicom-Burnner",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 7,
    "ae_title": "GinkGo",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 8,
    "ae_title": "CT-01",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 9,
    "ae_title": "X-Ray",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 10,
    "ae_title": "Dicom-Burnner",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 11,
    "ae_title": "GinkGo",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 12,
    "ae_title": "CT-01",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 13,
    "ae_title": "X-Ray",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 14,
    "ae_title": "Dicom-Burnner",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 15,
    "ae_title": "GinkGo",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 16,
    "ae_title": "CT-01",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 17,
    "ae_title": "X-Ray",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 18,
    "ae_title": "Dicom-Burnner",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 19,
    "ae_title": "GinkGo",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 20,
    "ae_title": "CT-01",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 21,
    "ae_title": "X-Ray",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 22,
    "ae_title": "Dicom-Burnner",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 23,
    "ae_title": "GinkGo",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 24,
    "ae_title": "CT-01",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 25,
    "ae_title": "X-Ray",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 26,
    "ae_title": "Dicom-Burnner",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 27,
    "ae_title": "GinkGo",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
  {
    "id": 28,
    "ae_title": "CT-01",
    "ip_address": "198.234.234.44",
    "port": 104,
    "device_name": "Radiology",
    "description": "to the DICOM protocol on the remote modality (usually 104)",
  },
]